$(".livro3").click(function(){
  $(".livro3").addClass("livro3click");
  $(".livro4").removeClass("livro4click");
  $(".livro5").removeClass("livro5click");
  $(".livro6").removeClass("livro6click");
  $(".livro7").removeClass("livro7click");
  $(".livro9").removeClass("livro9click");
  $(".livro10").removeClass("livro10click");
  $(".caixa-img").addClass("esconde");
  $(".boneco1").removeClass("esconde");
});
$(".livro4").click(function(){
  $(".livro3").removeClass("livro3click");
  $(".livro4").addClass("livro4click");
  $(".livro5").removeClass("livro5click");
  $(".livro6").removeClass("livro6click");
  $(".livro7").removeClass("livro7click");
  $(".livro9").removeClass("livro9click");
  $(".livro10").removeClass("livro10click");
  $(".caixa-img").addClass("esconde");
  $(".boneco2").removeClass("esconde");
});
$(".livro5").click(function(){
  $(".livro3").removeClass("livro3click");
  $(".livro4").removeClass("livro4click");
  $(".livro5").addClass("livro5click");
  $(".livro6").removeClass("livro6click");
  $(".livro7").removeClass("livro7click");
  $(".livro9").removeClass("livro9click");
  $(".livro10").removeClass("livro10click");
  $(".caixa-img").addClass("esconde");
  $(".boneco3").removeClass("esconde");
});
$(".livro6").click(function(){
  $(".livro3").removeClass("livro3click");
  $(".livro4").removeClass("livro4click");
  $(".livro5").removeClass("livro5click");
  $(".livro6").addClass("livro6click");
  $(".livro7").removeClass("livro7click");
  $(".livro9").removeClass("livro9click");
  $(".livro10").removeClass("livro10click");
  $(".caixa-img").addClass("esconde");
  $(".boneco4").removeClass("esconde");
});
$(".livro7").click(function(){
  $(".livro3").removeClass("livro3click");
  $(".livro4").removeClass("livro4click");
  $(".livro5").removeClass("livro5click");
  $(".livro6").removeClass("livro6click");
  $(".livro7").addClass("livro7click");
  $(".livro9").removeClass("livro9click");
  $(".livro10").removeClass("livro10click");
  $(".caixa-img").addClass("esconde");
  $(".boneco5").removeClass("esconde");
});
$(".livro9").click(function(){
  $(".livro3").removeClass("livro3click");
  $(".livro4").removeClass("livro4click");
  $(".livro5").removeClass("livro5click");
  $(".livro6").removeClass("livro6click");
  $(".livro7").removeClass("livro7click");
  $(".livro9").addClass("livro9click");
  $(".livro10").removeClass("livro10click");
  $(".caixa-img").addClass("esconde");
  $(".boneco6").removeClass("esconde");
});
$(".livro10").click(function(){
  $(".livro3").removeClass("livro3click");
  $(".livro4").removeClass("livro4click");
  $(".livro5").removeClass("livro5click");
  $(".livro6").removeClass("livro6click");
  $(".livro7").removeClass("livro7click");
  $(".livro9").removeClass("livro9click");
  $(".livro10").addClass("livro10click");
  $(".caixa-img").addClass("esconde");
  $(".boneco7").removeClass("esconde");
});
$(".container").dblclick(function(){
  $(".livro3").removeClass("livro3click");
  $(".livro4").removeClass("livro4click");
  $(".livro5").removeClass("livro5click");
  $(".livro6").removeClass("livro6click");
  $(".livro7").removeClass("livro7click");
  $(".livro9").removeClass("livro9click");
  $(".livro10").removeClass("livro10click");
  $(".caixa-img").addClass("esconde");
});
